extends: eslint-config-gjs

parserOptions:
  ecmaVersion: 6

rules:
  camelcase:
    - error
    - properties: always
  indent:
    - error
    - 2
  no-trailing-spaces: error
  'prefer-const': 'error'
