extends: eslint-config-gjs

parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    impliedStrict: true

rules:
  camelcase:
    - error
    - properties: always
  indent:
    - error
    - 2
  no-trailing-spaces: error
  'prefer-const': 'error'
  object-curly-spacing:
    - error
    - always
